services:
  postgres:
    image: postgres:latest
    container_name: openwatch_postgres
    environment:
      POSTGRES_USER: openwatch
      POSTGRES_PASSWORD: openwatch
      POSTGRES_DB: openwatch
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
